global:
  scrape_interval: 20s # default scrape target is 15 seconds
  evaluation_interval: 20s # default scrape target is 15 seconds
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with external systems
  # external_labels:
  #   monitor: "my-project"

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
# rule_files:
# - "alert.rules"
# - "first.rules"
# - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: myapp
    scrape_interval: 10s
    static_configs:
      - targets:
          - golang:8080
